on:
  push:
    tags:
      - 'v*'

name: Release

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Release Notes
        id: release_notes
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            COMMITS=$(git log --pretty=format:"* %s (%h)" --reverse)
          else
            COMMITS=$(git log ${PREVIOUS_TAG}..HEAD --pretty=format:"* %s (%h)" --reverse)
          fi
          
          {
            echo "## What's Changed"
            echo ""
            echo "$COMMITS"
          } >> "$GITHUB_STEP_SUMMARY"
          
          echo "CHANGELOG<<EOF" >> "$GITHUB_ENV"
          echo "## What's Changed" >> "$GITHUB_ENV"
          echo "" >> "$GITHUB_ENV"
          echo "$COMMITS" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: ${{ contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}